#!/usr/bin/python3
import sys
import os
from pathlib import Path
script_template = """#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pwncus import *

context.log_level = 'debug'
exe = context.binary = ELF('./{exe_path}', checksec=False)
libc = exe.libc

def start(argv=[], *a, **kw):
    if args.GDB:
        return gdb.debug([exe.path] + argv, gdbscript='''
        init-pwndbg

        c
        '''.format(**locals()), *a, **kw)
    elif args.REMOTE:
        return remote(sys.argv[1], sys.argv[2], *a, **kw)
    else:
        return process([exe.path] + argv, *a, **kw)

p = start()

# ==================== EXPLOIT ====================

def exploit():



  interactive()

if __name__ == '__main__':
  exploit()
"""

def main():
    if len(sys.argv) < 2:
        print("Usage: genpwn <binary_path>")
        sys.exit(1)

    binary_path = sys.argv[1]

    script_content = script_template.format(
        exe_path = binary_path
    )

    exploit_path = Path("xpl.py")
    exploit_path.write_text(script_content)
    exploit_path.chmod(0o755)

    binary_file = Path(binary_path)
    if binary_file.exists():
        binary_file.chmod(0o755)

    os.system(f"subl {exploit_path}")

if __name__ == "__main__":
    main()
